baseURL = "/"
languageCode = "es-mx"
title = "Proyecto Miyotl"
theme = "personal-web"
copyright = "©Proyecto Miyotl"
enableEmoji=true

[params.intro]
  main = "Miyotl App"
  sub = "App que busca preservar las lenguas mexicanas"

[params.notFound]
  gopher = "/images/ajolote-triste.png"
  h1 = 'Página no encontrada :('
  p = "Esta página no existe o está en construcción..."

[params.main]
  latestPublishHeader = " "

[params.social]
  facebook = "https://www.facebook.com/MiyotlApp"
  twitter = "https://twitter.com/MiyotlApp"
  instagram = "https://www.instagram.com/miyotl.app"
  youtube = "https://www.youtube.com/channel/UC1xNNKPlRotin_aJ1kW2pkQ"
  github = "https://github.com/miyotl"
  discord = "https://discord.gg/98RUGCq"
  
[params.contact]
  email = "mesa@miyotl.org"
  text = "Mándanos un correo ✉️"

[params.sidebar]
  logo = "images/icon-full.png"
  backgroundImage = "images/sidebar.png"
  
[markup.goldmark.renderer]
  unsafe = true

[menu]

# [[menu.main]]
#   identifier = "acerca"
#   name = "Conoce al equipo"
#   title = "Conoce al equipo"
#   url = "/acerca/"
#   weight = 1

